### PR TITLE
Fixed get-volume

### PR DESCRIPTION
**Pull request by EladBezalel**
get-volume.exe didn't worked, but set-volume with no parameters returned the current volume

### CODE REVIEW

**Comment by EladBezalel** [comment]
Btw i think this should be separated to another repo as done with linux and mac

**Comment by kevva** [comment]
I can't get this to work in node.

**Comment by EladBezalel** [comment]
I've checked with the test.js and it worked

Edit: I've checked with require and it worked :)

**Comment by kevva** [comment]
Nah, it doesn't write to `stdout` so I'm not sure how to capture the output.

**Comment by gillstrom** [comment]
`stdout` is empty for me as well.

**Comment by EladBezalel** [comment]
weird.. it works for me
image
image

Edit:
Can you check if volume.exe is returning any output?
image

**Comment by gillstrom** [comment]
`volume.exe` works indeed, but it doesn't work in node for some reason.

**Comment by kevva** [comment]
http://stackoverflow.com/questions/4640106/get-the-current-system-volume-in-windows-7/4640225#comment49697293_21056089

**Comment by EladBezalel** [comment]
yea so comment below he added the [flush](http://sourceforge.net/projects/mplayer-edl/files/current_system_volume_vista_plus_flush.exe/download)

**Comment by kevva** [comment]
Yeah, but the new binary isn't statically compiled so it will crash on people that doesn't have those headers. I'm just going to compile a new one.

**Comment by EladBezalel** [comment]
it crashed with missing ibgcc_s_dw2-1.dll..
What's the solution? where did you get set-volume.exe?

**Comment by kevva** [comment]
Should be fixed now.

**Comment by EladBezalel** [comment]
Great work thanks again!

**Pull request merged**
